[tool.black]
line-length = 88
target-version = ["py311"]
exclude = ["venv", "build", "dist"]

[tool.ruff]
target-version = "py311"
line-length = 88
# "select" means what Ruff will check for
select = ["E", "F", "I"]
# "ignore" means what Ruff will skip
ignore = ["E203", "W503"]
# Tell Ruff to also sort imports like isort
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["utilities", "pages"]
combine-as-imports = true
